// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO comments (lesson_id, user_id, body)
VALUES ($1, $2, $3)
`

type CreateCommentParams struct {
	LessonID int32  `json:"lesson_id"`
	UserID   int32  `json:"user_id"`
	Body     string `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.Exec(ctx, createComment, arg.LessonID, arg.UserID, arg.Body)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1 AND user_id = $2
`

type DeleteCommentParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.UserID)
	return err
}

const listCommentsByLesson = `-- name: ListCommentsByLesson :many
SELECT c.id, c.lesson_id, c.user_id, c.body, c.created_at, u.name AS user_name
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.lesson_id = $1
ORDER BY c.created_at ASC
`

type ListCommentsByLessonRow struct {
	ID        int32              `json:"id"`
	LessonID  int32              `json:"lesson_id"`
	UserID    int32              `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserName  string             `json:"user_name"`
}

func (q *Queries) ListCommentsByLesson(ctx context.Context, lessonID int32) ([]ListCommentsByLessonRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByLesson, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByLessonRow{}
	for rows.Next() {
		var i ListCommentsByLessonRow
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
