// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCourse = `-- name: GetCourse :one
SELECT
    c.id,
    c.title,
    c.description,
    c.instructor,
    c.created_at,
    COALESCE(ROUND(AVG(r.stars)::numeric, 1), 0)::float8 AS avg_rating,
    COUNT(r.id)::int AS rating_count
FROM courses c
LEFT JOIN ratings r ON r.course_id = c.id
WHERE c.id = $1
GROUP BY c.id
`

type GetCourseRow struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Instructor  string             `json:"instructor"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AvgRating   float64            `json:"avg_rating"`
	RatingCount int32              `json:"rating_count"`
}

func (q *Queries) GetCourse(ctx context.Context, id int32) (GetCourseRow, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i GetCourseRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Instructor,
		&i.CreatedAt,
		&i.AvgRating,
		&i.RatingCount,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT
    c.id,
    c.title,
    c.description,
    c.instructor,
    c.created_at,
    COALESCE(ROUND(AVG(r.stars)::numeric, 1), 0)::float8 AS avg_rating,
    COUNT(r.id)::int AS rating_count
FROM courses c
LEFT JOIN ratings r ON r.course_id = c.id
GROUP BY c.id
ORDER BY c.id
`

type ListCoursesRow struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Instructor  string             `json:"instructor"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AvgRating   float64            `json:"avg_rating"`
	RatingCount int32              `json:"rating_count"`
}

func (q *Queries) ListCourses(ctx context.Context) ([]ListCoursesRow, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoursesRow{}
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Instructor,
			&i.CreatedAt,
			&i.AvgRating,
			&i.RatingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
