// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollments.sql

package db

import (
	"context"
)

const enrollUser = `-- name: EnrollUser :exec
INSERT INTO enrollments (user_id, course_id)
VALUES ($1, $2)
ON CONFLICT (user_id, course_id) DO NOTHING
`

type EnrollUserParams struct {
	UserID   int32 `json:"user_id"`
	CourseID int32 `json:"course_id"`
}

func (q *Queries) EnrollUser(ctx context.Context, arg EnrollUserParams) error {
	_, err := q.db.Exec(ctx, enrollUser, arg.UserID, arg.CourseID)
	return err
}

const isEnrolled = `-- name: IsEnrolled :one
SELECT EXISTS (
    SELECT 1 FROM enrollments WHERE user_id = $1 AND course_id = $2
) AS enrolled
`

type IsEnrolledParams struct {
	UserID   int32 `json:"user_id"`
	CourseID int32 `json:"course_id"`
}

func (q *Queries) IsEnrolled(ctx context.Context, arg IsEnrolledParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEnrolled, arg.UserID, arg.CourseID)
	var enrolled bool
	err := row.Scan(&enrolled)
	return enrolled, err
}
