// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package db

import (
	"context"
)

const getLesson = `-- name: GetLesson :one
SELECT id, course_id, title, body, "order", created_at
FROM lessons
WHERE id = $1
`

func (q *Queries) GetLesson(ctx context.Context, id int32) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLesson, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Body,
		&i.Order,
		&i.CreatedAt,
	)
	return i, err
}

const listLessonsByCourse = `-- name: ListLessonsByCourse :many
SELECT id, course_id, title, body, "order", created_at
FROM lessons
WHERE course_id = $1
ORDER BY "order", id
`

func (q *Queries) ListLessonsByCourse(ctx context.Context, courseID int32) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Body,
			&i.Order,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
