// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Course struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Instructor  string             `json:"instructor"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Enrollment struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	CourseID   int32              `json:"course_id"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

type Rating struct {
	ID        int32              `json:"id"`
	CourseID  int32              `json:"course_id"`
	UserID    int32              `json:"user_id"`
	Stars     int16              `json:"stars"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
