// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package db

import (
	"context"
)

const getRatingByUserAndCourse = `-- name: GetRatingByUserAndCourse :one
SELECT id, course_id, user_id, stars, created_at
FROM ratings
WHERE course_id = $1 AND user_id = $2
`

type GetRatingByUserAndCourseParams struct {
	CourseID int32 `json:"course_id"`
	UserID   int32 `json:"user_id"`
}

func (q *Queries) GetRatingByUserAndCourse(ctx context.Context, arg GetRatingByUserAndCourseParams) (Rating, error) {
	row := q.db.QueryRow(ctx, getRatingByUserAndCourse, arg.CourseID, arg.UserID)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.Stars,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRating = `-- name: UpsertRating :one
INSERT INTO ratings (course_id, user_id, stars)
VALUES ($1, $2, $3)
ON CONFLICT (course_id, user_id)
DO UPDATE SET stars = EXCLUDED.stars
RETURNING id, course_id, user_id, stars, created_at
`

type UpsertRatingParams struct {
	CourseID int32 `json:"course_id"`
	UserID   int32 `json:"user_id"`
	Stars    int16 `json:"stars"`
}

func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, upsertRating, arg.CourseID, arg.UserID, arg.Stars)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.Stars,
		&i.CreatedAt,
	)
	return i, err
}
